### ISSUE TITLE
【SOLVED】Can't call numpy() on Tensor that requires grad. Use tensor.detach().numpy() instead.

### ISSUE THREAD

**Issue by 0x6r1an0y** [XiaMooo/Yolo-Detect-Layer-Visualization#1]
在使用yolov7_multi_head_cls_letterbox_with_auto時遇到的小bug，疑似是numpy版本相容(兼容)問題？

>   File "test_visual.py", line 113, in plot_multi_heatmap
>     array = array.cpu().numpy()
> RuntimeError: Can't call numpy() on Tensor that requires grad. Use tensor.detach().numpy() instead.

```python
def plot_multi_heatmap(*arrays, cmap='viridis', title=None, row=None, col=None):
......
    for i, array in enumerate(arrays):
        if isinstance(array, torch.Tensor):
           array = array.cpu().numpy()
        r = i // col
        c = i % col
        axi = ax[r, c] if row > 1 else ax[c]
        sns.heatmap(array, square=True, cmap=cmap, ax=axi)
    plt.show()
```
在這個function底下找到`array = array.cpu().numpy()`，將它添加一個參數`array = array.cpu().numpy(force=True)`就可以使用了

環境（跟yolov7原生用同一個環境）：
windows11+anaconda
python 3.8.19
numpy==1.23.5
seaborn==0.13.2
torch==2.3.1+cu121
torchaudio==2.3.1+cu121
torchvision==0.18.1+cu121

**Comment by XiaMooo** [comment]
这个方式有点暴力哈，实际上产生这个错误的原因是某些pytorch张量是记录梯度的(requires_grad=True)，所以安全的解决方法应该是将 `array = array.cpu().numpy()` 变为 `array = array.detach().cpu().numpy()` ，使其在转到CPU前先先拷贝一份记录梯度的备份。

**Comment by XiaMooo** [comment]
这个方式有点暴力哈，实际上产生这个错误的原因是某些pytorch张量是记录梯度的(requires_grad=True)，所以安全的解决方法应该是将`array = array.cpu().numpy()`

**Comment by 0x6r1an0y** [comment]
啊…原來detach()是要加在那邊啊，我才剛玩pytorch沒多久不知道怎麼正確處理，獻醜了
